server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: User Registration Email Verification

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true

  mail:
    host: maildev
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls.enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
